on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          npm ci
          npm run build
          git config user.name "Zasda Yusuf Mikail"
          git config user.email "zasdaym@gmail.com"
          git checkout -b gh-pages
          rm -rf .gitignore
          git add public/
          git commit -m "Update"
          git push origin gh-pages
