on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
      - uses: EndBug/add-and-commit@v8
        with:
          add: public/
          default_author: user_info
          message: Update
          new_branch: gh-pages
